# Generated by Django 5.1.6 on 2026-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='stock_deducted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
