# Generated by Django 5.1.6 on 2026-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_promotion_promotionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='home_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorie',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
