# Generated by Django 5.1.6 on 2026-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_categorie_home_order_categorie_show_on_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='home_order',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='show_on_home',
        ),
        migrations.AddField(
            model_name='product',
            name='home_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
