# Generated by Django 5.1.6 on 2026-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_categorie_home_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Code-barres'),
        ),
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.PositiveIntegerField(default=2, verbose_name='Stock minimum'),
        ),
    ]
