# Generated by Django 5.1.6 on 2025-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marques/'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la marque'),
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
