# Generated by Django 5.1.6 on 2026-04-20 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Entrez un numéro de téléphone valide.', regex='^\\+?[0-9\\s\\-]{9,20}$')])),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
